# most this config comes from https://dev.to/iggredible/useful-tmux-configuration-examples-k3g

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

bind r source-file ~/.tmux.conf \; display-message "Reloaded!"

# Set prefix to Control + a 
unbind C-a
set -g prefix C-a
bind C-a send-prefix

# Don't make escape slow in Nvim
set -s escape-time 0

# Enable mouse support
set -g mouse on

# Send session name to terminal (for WezTerm tab titles)
set -g set-titles on
set -g set-titles-string '#S'

# Increase history limit
set -g history-limit 10000

# Don't use 0 base since 0 is at the end of the number keys
set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

# more sensible split window commands
bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"

bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

# space to toggle between last two windows
bind C-a last-window

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim copy mode
setw -g mode-keys vi

# Easier resizing
bind -r C-j resize-pane -D  15 
bind -r C-k resize-pane -U  15 
bind -r C-h resize-pane -L  30 
bind -r C-l resize-pane -R  30 

set -g status-bg black
set -g status-fg white

# Make the active pane border thicker and gold/yellow
set -g pane-active-border-style 'fg=yellow,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'
# set -g pane-border-lines heavy

setw -g clock-mode-color yellow
setw -g mode-style "fg=black bg=yellow bold"

set -g status-position bottom

set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'maxpetretta/tmux-monokai-pro'

run '~/.tmux/plugins/tpm/tpm'
